function ensureJSPDFLoaded() {
    return new Promise((resolve) => {
        if (window.jspdf) {
            resolve(window.jspdf);
            return;
        }
        const script = document.createElement('script');
        script.src = 'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js';
        script.onload = () => resolve(window.jspdf);
        document.head.appendChild(script);
    });
}

export async function exportProposalToPDF(proposal) {
    const jspdf = await ensureJSPDFLoaded();
    const doc = new jspdf.jsPDF();
    
    const margin = 20;
    const pageWidth = doc.internal.pageSize.getWidth();
    let yPos = margin;

    // Cover Page
    doc.setFontSize(24);
    doc.setFont("helvetica", "bold");
    doc.text(proposal.title || "Proposal", pageWidth / 2, 80, { align: "center" });
    
    doc.setFontSize(14);
    doc.setFont("helvetica", "normal");
    doc.text(`Prepared for: ${proposal.companyName || "Client"}`, pageWidth / 2, 100, { align: "center" });
    doc.text(`Date: ${new Date().toLocaleDateString()}`, pageWidth / 2, 110, { align: "center" });
    
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text("CONFIDENTIAL", pageWidth / 2, 130, { align: "center" });

    // Badges (Simulated text for now)
    doc.setTextColor(0, 150, 0);
    doc.text(`Audit Score: ${proposal.auditScore || '95/100'}`, pageWidth / 2, 150, { align: "center" });
    doc.text(`Win Probability: ${proposal.winProbability || '87%'}`, pageWidth / 2, 160, { align: "center" });

    doc.addPage();
    
    // Content sections
    doc.setTextColor(0, 0, 0);
    const sections = proposal.sections || [
        { title: 'Executive Summary', content: 'Summary goes here...' },
        { title: 'Technical Approach', content: 'Approach goes here...' },
        { title: 'Pricing', content: 'Pricing details...' }
    ];

    sections.forEach((sec, idx) => {
        if (yPos > 250) {
            doc.addPage();
            yPos = margin;
        }
        doc.setFontSize(16);
        doc.setFont("helvetica", "bold");
        doc.text(sec.title, margin, yPos);
        yPos += 10;
        
        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        const lines = doc.splitTextToSize(sec.content, pageWidth - margin * 2);
        
        lines.forEach(line => {
            if (yPos > 270) {
                doc.addPage();
                yPos = margin;
            }
            doc.text(line, margin, yPos);
            yPos += 6;
        });
        
        yPos += 10;
    });

    // Add footer to all pages
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(100, 100, 100);
        doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, 285, { align: 'right' });
        doc.text("Generated by ArchEngine AI | AI-assisted — not guaranteed", margin, 285);
    }

    doc.save(`${proposal.title?.replace(/\\s+/g, '_') || 'Proposal'}.pdf`);
}

export async function exportToGoogleDocs(proposal) {
    if (confirm("This requires Google Workspace connection. Proceed?")) {
        try {
            await fetch('/api/connectors/google/push-doc', {
                method: 'POST',
                body: JSON.stringify(proposal),
                headers: { 'Content-Type': 'application/json' }
            });
            alert("Exported to Google Docs!");
        } catch (e) {
            console.error(e);
            alert("Failed to export to Google Docs.");
        }
    }
}

export function downloadProposalAsText(proposal) {
    let text = `${proposal.title || 'Proposal'}\\n\\n`;
    const sections = proposal.sections || [];
    sections.forEach(s => {
        text += `=== ${s.title} ===\\n${s.content}\\n\\n`;
    });
    
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${proposal.title?.replace(/\\s+/g, '_') || 'Proposal'}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}
